version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{S3_BUCKET}}"
        BUILD_FOLDER: "dist"
phases:
    install:
        runtime-versions:
            nodejs: 14
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - npm install -g @angular/cli
    build:
        commands:
            - echo Build started on `date`
            - ng build
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
